name: Supabase Keepalive

on:
  schedule:
    # Run twice per week: Mondays and Thursdays at 9 AM UTC
    - cron: '0 9 * * 1,4'
  workflow_dispatch: # Allow manual triggering

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET \
            "${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/rest/v1/profiles?select=count" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}")
          
          if [ $response -eq 200 ]; then
            echo "✅ Supabase keepalive successful (HTTP $response)"
          else
            echo "❌ Supabase keepalive failed (HTTP $response)"
            exit 1
          fi